import turtle, random
apals = turtle.Turtle()
apals.begin_fill()
apals.color("green")
apals.up()
apals.setpos(100, -20)
apals.down()
apals.circle(70)
apals.end_fill()

trissturis = turtle.Turtle()
trissturis.begin_fill()
trissturis.color("blue")
trissturis.setpos(0, -1)
trissturis.circle(20, steps=3)
trissturis.end_fill()

figeras =turtle.Turtle()
figeras.begin_fill()
figeras.color("black")
figeras.up()
figeras.setpos(90, -120)
figeras.down()
figeras.circle(40, steps=10)
figeras.end_fill()
